### ISSUE TITLE
handle when a relative path is referenced and failed

### ISSUE THREAD

**Issue by zanarmstrong** [enjalot/building-blocks#19]
Many (of mbostock's) example blocks have a required file with a relative path, especially for geo examples. 

For example: Coastal Graph Distance
http://bl.ocks.org/mbostock/9744818

When bringing it into building blocks, it just shows up blank.  :(

The path is passed to d3.json as: "/mbostock/raw/4090846/us.json"

I'm not sure what the answer is, but should be handled in some way.  On a simple level, maybe just a warning message.  Better if there is a workaround to bring in the file somehow.  Best if something happens automatically to make it work :)

**Comment by enjalot** [comment]
From our in person discussion:
We don't want to support the relative paths because they break the design principle that code should be able to copy pasted from the building blocks environment to a local web development environment.

A potential solution would be to detect when this is happening with some regex and then flag a warning on the line in CodeMirror.
We could also show a more helpful warning in the block render frame to encourage people to check the code when this happens. (the blank box is intimidating and discouraging)

**Comment by enjalot** [comment]
I've solved the problem of rendering blocks that use that specific pattern and file (which as far as I can tell is the only block being referenced in this way.
We should probably still show a message of some sort when we discover this. Perhaps if we have a modal system in place we can just bring it up on page load when its detected the first time.

**Comment by enjalot** [comment]
I'm going to go ahead and close this issue. I've greatly improved the way we handle loading gist files for use in <script> tags, <link> tags (for style sheets) and d3.json/csv/etc requests. It should be pretty robust: 
https://github.com/enjalot/building-blocks/blob/master/public/js/utils/parseCode.js
