### ISSUE TITLE
Optional transition from one property to a next when possible

### ISSUE THREAD

**Issue by emeeks** [enjalot/building-blocks#48]
It would be nice if there was a global "duration" property and any change in a style or attribute was actually transitioned to the new style/attribute, rather than a complete rerendering.

I realize this is a major feature request, but animated transitions are in data visualization because we know it helps people to follow how one thing changes to another.

**Comment by shobhitg** [comment]
Relevant: (http://stackoverflow.com/a/2024544/360844)[http://stackoverflow.com/a/2024544/360844]

**Comment by shobhitg** [comment]
Relevant: [http://stackoverflow.com/a/2024544/360844](http://stackoverflow.com/a/2024544/360844)

**Comment by curran** [comment]
This is a difficult feature to implement, because the way the editor is re-running the code would need to be changed completely. Currently the editor can run arbitrary HTML + JS code, and I think in order to make this idea work, some sort of restriction or limitation would need to be imposed on the kinds of code that can run. Maybe it would work for CSS, but I'm not sure how it could be achieved for arbitrary JavaScript. The JS would need to be written in such a way that it could be executed many times (i.e. stristly follow the D3 enter/update/exit scheme throughout the code).

One way might be to somehow compute the diff between states, then execute the things that changed within the existing environment (without tearing down and re-building the DOM). This is one of the main issues addressed by Chiasm - see how in this [Chiasm Layout Example](http://bl.ocks.org/curran/3f0b1128d74308fc8fe1) you can use the Inlet slider to change configuration, and the updates happen right away, within the existing DOM structure.

**Comment by enjalot** [comment]
Yes, it's difficult to implement and theoretically (but not practically) impossible (thanks Turing...) to do the way I've centered the UI around an index.html file. As @curran notes you'd have to interpret the user's code, which could be any combination of valid html (including things like iframes) and figure out how to gracefully transition state. For more details on the architecture built to support rendering the index.html see my writeup: https://medium.com/@enjalot/architecting-a-sandbox-97b211937911

This would be a much easier problem to solve in a system that separates code into it's individual parts (JS/CSS/HTML) like Tributary, CodePen or JSFiddle. I explicitly chose to go away from that model with building-blocks because I found that more nuanced control over code had much less impact than accessibility. The reality is that its going to take a lot of design, dev and testing to build a better editor than Sublime Text, Atom or even Visual Studio (the most instrumented dev platform in existence). The problem I'm trying to solve here is one of getting started, eliminating the friction from getting the ball rolling. Once the ball is rolling people will go back to editing in their favorite editor, perhaps only using building-blocks to quickly upload/tweak/fork something. I don't expect them to live in the editor (altho I will likely do so as I love to write examples that end up < 200 lines of code).

With all that said I will close this issue, but I do not dismiss it. Building blocks is the product of my lessons learned in Tributary, it is a conscious swing of the pendulum away from instrumentation. There is always room for more gist-backed (but hopefully blocks compatible) online code editors!
