### ISSUE TITLE
defer attribute in script tag doesn't work with local files

### ISSUE THREAD

**Issue by datummm** [enjalot/building-blocks#64]
Since building-blocks directly replaces script references to local files with code, the defer attribute in script tags does not work (it only works with non-inline code). This can create issues with blocks where there are internal and external scripts with defer tags; the internal scripts will load and execute before any external scripts with the defer tag, which may not be the intended behavior.

[Example of the issue](http://blockbuilder.org/kenpenn/dd72bb9365543c52ce70). [MDN reference to script/defer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script).

**Comment by enjalot** [comment]
I think at the end of the day this isn't worth addressing. I grepped over 5000 blocks and this example is the only one that uses the `defer` keyword, I've reached out to the author to ask him to remove it since it's not actually necessary in this case.

I attempted using data URI to supply the javascript code to the script tag, allowing the defer keyword to work. This won't work because btoa doesn't support unicode so that's a non-starter.

Eventually I'd like to make a sort of warning system that allows us to let the code author know when they do something unsupported by blockbuilder (using relative blocks URLS is another common anti-pattern that I could alert people to).
